// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e8637dcc282c405e "DaVinci Watches - Finale", do not edit manually */
"use client";

// virtual:formulairecontact
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/formulairecontact-UOf6.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS, withFX } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ImageWithFX = withFX(Image);
var cycleOrder = ["j1Z55qcqc", "fix20bDDw", "Ob7TbTd3D", "tva8lGOpT"];
var serializationHash = "framer-RjZrA";
var variantClassNames = { fix20bDDw: "framer-v-fvwb9z", j1Z55qcqc: "framer-v-qlae4m", Ob7TbTd3D: "framer-v-axk1ju", tva8lGOpT: "framer-v-qzxcj4" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};
var animation = { opacity: 0, rotate: 0, rotateX: 0, rotateY: 0, scale: 1, skewX: 0, skewY: 0, x: -150, y: 0 };
var transition2 = { damping: 50, delay: 0.1, mass: 1, stiffness: 100, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { Desktop: "j1Z55qcqc", Laptop: "fix20bDDw", Phone: "tva8lGOpT", Tablet: "Ob7TbTd3D" };
var getProps = ({ height, id, image, width, ...props }) => {
  return { ...props, rMshSWyfZ: image ?? props.rMshSWyfZ ?? { alt: "hotel", pixelHeight: 4e3, pixelWidth: 6e3, src: "https://framerusercontent.com/images/DVniB5aTivyBCtyIXaP04XwJZtU.jpg?scale-down-to=2048", srcSet: "https://framerusercontent.com/images/DVniB5aTivyBCtyIXaP04XwJZtU.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/DVniB5aTivyBCtyIXaP04XwJZtU.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/DVniB5aTivyBCtyIXaP04XwJZtU.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/DVniB5aTivyBCtyIXaP04XwJZtU.jpg?scale-down-to=4096 4096w,https://framerusercontent.com/images/DVniB5aTivyBCtyIXaP04XwJZtU.jpg 6000w" }, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "j1Z55qcqc" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, rMshSWyfZ, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "j1Z55qcqc", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsxs(motion.section, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-qlae4m", className, classNames), "data-framer-name": "Desktop", layoutDependency, layoutId: "j1Z55qcqc", ref: refBinding, style: { backgroundColor: "var(--token-3399e391-f9d3-4781-bcc9-e38e7cf0c7f5, rgb(249, 253, 254))", ...style }, ...addPropertyOverrides({ fix20bDDw: { "data-framer-name": "Laptop" }, Ob7TbTd3D: { "data-framer-name": "Tablet" }, tva8lGOpT: { "data-framer-name": "Phone" } }, baseVariant, gestureVariant), children: [/* @__PURE__ */ _jsx(motion.div, { className: "framer-72otws", "data-framer-name": "Container", layoutDependency, layoutId: "Bmk0gDNoN", children: /* @__PURE__ */ _jsx(motion.div, { className: "framer-hsal8n", "data-framer-name": "Form", layoutDependency, layoutId: "KHQq7WoAY" }) }), /* @__PURE__ */ _jsx(ImageWithFX, { __framer__animate: { transition: transition2 }, __framer__animateOnce: true, __framer__enter: animation, __framer__styleAppearEffectEnabled: true, __framer__threshold: 0, __perspectiveFX: false, __smartComponentFX: true, __targetOpacity: 1, background: { alt: "", fit: "fill", loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 80), pixelHeight: 4e3, pixelWidth: 6e3, sizes: `calc(${componentViewport?.width || "100vw"} * 0.7)`, ...toResponsiveImage(rMshSWyfZ) }, className: "framer-trkrvl", "data-framer-name": "Image", layoutDependency, layoutId: "fUa6NH0oR", ...addPropertyOverrides({ tva8lGOpT: { background: { alt: "", fit: "fill", loading: getLoadingLazyAtYPosition((componentViewport?.y || 0) + 80), pixelHeight: 4e3, pixelWidth: 6e3, sizes: componentViewport?.width || "100vw", ...toResponsiveImage(rMshSWyfZ) } } }, baseVariant, gestureVariant) })] }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-RjZrA.framer-j43q2h, .framer-RjZrA .framer-j43q2h { display: block; }", ".framer-RjZrA.framer-qlae4m { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 160px 64px 160px 64px; position: relative; width: 1560px; }", ".framer-RjZrA .framer-72otws { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; max-width: 1640px; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-RjZrA .framer-hsal8n { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: flex-end; min-height: 798px; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-RjZrA .framer-trkrvl { bottom: 80px; flex: none; left: 0px; position: absolute; top: 80px; width: 70%; z-index: 0; }", ".framer-RjZrA.framer-v-fvwb9z.framer-qlae4m { width: 1200px; }", ".framer-RjZrA.framer-v-axk1ju.framer-qlae4m { padding: 160px 40px 160px 40px; width: 810px; }", ".framer-RjZrA.framer-v-axk1ju .framer-hsal8n, .framer-RjZrA.framer-v-qzxcj4 .framer-hsal8n { min-height: 318px; }", ".framer-RjZrA.framer-v-qzxcj4.framer-qlae4m { padding: 160px 24px 160px 24px; width: 390px; }", ".framer-RjZrA.framer-v-qzxcj4 .framer-trkrvl { right: 0px; width: unset; }"];
var Framerm_PRyUvCe = withCSS(Component, css, "framer-RjZrA");
var stdin_default = Framerm_PRyUvCe;
Framerm_PRyUvCe.displayName = "formulairecontact";
Framerm_PRyUvCe.defaultProps = { height: 1117.5, width: 1560 };
addPropertyControls(Framerm_PRyUvCe, { variant: { options: ["j1Z55qcqc", "fix20bDDw", "Ob7TbTd3D", "tva8lGOpT"], optionTitles: ["Desktop", "Laptop", "Tablet", "Phone"], title: "Variant", type: ControlType.Enum }, rMshSWyfZ: { __defaultAssetReference: "data:framer/asset-reference,DVniB5aTivyBCtyIXaP04XwJZtU.jpg?originalFilename=IMG_6764.jpg&preferredSize=auto", __vekterDefault: { alt: "hotel", assetReference: "data:framer/asset-reference,DVniB5aTivyBCtyIXaP04XwJZtU.jpg?originalFilename=IMG_6764.jpg&preferredSize=auto" }, title: "Image", type: ControlType.ResponsiveImage } });
addFonts(Framerm_PRyUvCe, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:formulairecontact
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "tva8lGOpT",
  "md": "Ob7TbTd3D",
  "xl": "fix20bDDw",
  "2xl": "j1Z55qcqc"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "ABs8A7Jd4": { "path": "/vente" }, "HqqUpNGKj": { "path": "/" }, "X4ktpndPG": { "path": "/404" }, "Xzx1dk12F": { "path": "/latelier" }, "w6N05sxE8": { "path": "/contact" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "ABs8A7Jd4": {
          "path": "/vente"
        },
        "HqqUpNGKj": {
          "path": "/"
        },
        "X4ktpndPG": {
          "path": "/404"
        },
        "Xzx1dk12F": {
          "path": "/latelier"
        },
        "w6N05sxE8": {
          "path": "/contact"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "e8637dcc282c405e8332e4eab2cb458a196f99fcac27567df85b0de9996f5033",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
